# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baa4555e06bb503169a317f34b82e0865dc44fa39df99901e73a1e222f907011bfde19b2b90ec7e49361e91dc98c386f90951fccc26ccf954c7680cbf59e21f3

test:
  secret_key_base: aa02aef5dd9a995921a927e7f2c5d3df6aef1ddfbd65c5bd9429dc6b4ea60bb27576df1163ef784e8aa68536e08c9cc327e95f09bd0e9af830c0c9468e255138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
